#!/bin/bash
cleanup () {
  pkill backend
}
trap cleanup exit

pg_ctl start

while true; do
  time dub build --build=release --skip-registry=all --nodeps
  ./backend &
  inotifywait -e modify,delete --exclude '/\.|/backend' -qr .
  pkill backend
done
